const focklynRyYnsagh = {
    fEnnaghtyn: [
        ["ta mee", "I am", [1, 0, 0]],
        ["kys t'ou?", "how are you?", [1, 0, 0]],
        ["vel oo?", "are you?", [1, 0, 0]],
        ["cha nel mee", "I'm not", [1, 0, 0]],
        ["braew", "fine", [0, 0, 0]],
        ["çheh", "hot", [0, 0, 0]],
        ["çhing", "sick", [0, 0, 0]],
        ["corree", "angry", [0, 0, 0]],
        ["feayr", "cold", [0, 0, 0]],
        ["greesit", "excited", [0, 0, 0]],
        ["maynrey", "happy", [0, 0, 0]],
        ["skee", "tired", [0, 0, 0]],
        ["trimshagh", "sad", [0, 0, 0]]
    ],
    fEarrooyn10: [
        ["cre'n eash t'ort?", "how old are you?", [1, 0, 0]],
        ["bleeaney d'eash", "years old", [1, 0, 0]],
        ["un vlein", "one year", [1, 0, 0]],
        ["daa vlein", "two years", [1, 0, 0]],
        ["nane", "one", [0, 0, 0]],
        ["jees", "two", [0, 0, 0]],
        ["tree", "three", [0, 0, 0]],
        ["kiare", "four", [0, 0, 0]],
        ["queig", "five", [0, 0, 0]],
        ["shey", "six", [0, 0, 0]],
        ["shiaght", "seven", [0, 0, 0]],
        ["hoght", "eight", [0, 0, 0]],
        ["nuy", "nine", [0, 0, 0]],
        ["jeih", "ten", [0, 0, 0]]
    ],
    fBuill: [
        ["c'raad?", "where?", [1, 0, 0]],
        ["beaghey", "live", [1, 0, 0]],
        ["ayns", "in", [1, 0, 0]],
        ["Doolish", "Douglas", [0, 0, 0]],
        ["Laksaa", "Laxey", [0, 0, 0]],
        ["Rhumsaa", "Ramsey", [0, 0, 0]],
        ["Purt-ny-hInshey", "Peel", [0, 0, 0]],
        ["Purt Çhiarn", "Port Erin", [0, 0, 0]],
        ["Purt-le-Moirrey", "Port St. Mary", [0, 0, 0]],
        ["Balley Chashtal", "Castletown", [0, 0, 0]]
    ],
    fBee: [
        ["cre?", "what?", [1, 0, 0]],
        ["s'laik lhiat", "you like", [1, 0, 0]],
        ["laik lhiat?", "do you like?", [1, 0, 0]],
        ["s'laik lhiam", "I like", [1, 0, 0]],
        ["cha laik lhiam", "I don't like", [1, 0, 0]],
        ["ooylyn", "apples", [0, 0, 0]],
        ["bagoon", "bacon", [0, 0, 0]],
        ["arran", "bread", [0, 0, 0]],
        ["caashey", "cheese", [0, 0, 0]],
        ["spollagyn", "chips", [0, 0, 0]],
        ["eeast", "fish", [0, 0, 0]],
        ["noiridyn", "oranges", [0, 0, 0]],
        ["pronnagyn", "sausages", [0, 0, 0]],
        ["lossreeyn", "vegetables", [0, 0, 0]]
    ],
    fLaaghyn: [
        ["cre'n laa t'ayn?", "what day is it?", [1, 0, 0]],
        ["she ... t'ayn", "it's ...", [1, 0, 0]],
        ["cha nee ... t'ayn", "it's not ...", [1, 0, 0]],
        ["jiu", "today", [1, 0, 0]],
        ["Jelune", "Monday", [0, 0, 0]],
        ["Jemayrt", "Tuesday", [0, 0, 0]],
        ["Jecrean", "Wednesday", [0, 0, 0]],
        ["Jerdein", "Thursday", [0, 0, 0]],
        ["Jeheiney", "Friday", [0, 0, 0]],
        ["Jesarn", "Saturday", [0, 0, 0]],
        ["Jedoonee", "Sunday", [0, 0, 0]]
    ],
    fEmshyr: [
        ["emshyr", "weather", [1, 0, 0]],
        ["yn", "the", [1, 0, 0]],
        ["vel eh?", "is it?", [1, 0, 0]],
        ["vel yn emshyr?", "is the weather?", [1, 0, 0]],
        ["ta'n", "the ... is", [1, 0, 0]],
        ["cha nel yn emshyr", "the weather's not", [1, 0, 0]],
        ["t'eh", "it's", [1, 0, 0]],
        ["cha nel eh", "it's not", [1, 0, 0]],
        ["sterrymagh", "stormy", [0, 0, 0]],
        ["grianagh", "sunny", [0, 0, 0]],
        ["bodjallagh", "cloudy", [0, 0, 0]],
        ["geayagh", "windy", [0, 0, 0]],
        ["ceau fliaghey", "raining", [0, 0, 0]],
        ["ceau sniaghtey", "snowing", [0, 0, 0]]
    ],
    fRoortyssyn: [
        ["bluckan-coshey", "football", [1, 0, 0]],
        ["roar", "bike", [1, 0, 0]],
        ["er", "on", [1, 0, 0]],
        ["y", "the", [1, 0, 0]],
        ["gee", "eat / eating", [0, 0, 0]],
        ["cloie", "play / playing", [0, 0, 0]],
        ["lhaih", "read / reading", [0, 0, 0]],
        ["markiaght", "ride / riding", [0, 0, 0]],
        ["roie", "run / running", [0, 0, 0]],
        ["cadley", "sleep / sleeping", [0, 0, 0]],
        ["snaue", "swim / swimming", [0, 0, 0]],
        ["shooyl", "walk / walking", [0, 0, 0]],
        ["jeeaghyn", "watching", [0, 0, 0]],
        ["çhellveeish", "television", [0, 0, 0]]
    ],
    fEmshyrChaie: [
        ["ren mee", "I did", [1, 0, 0]],
        ["cha ren mee", "I didn't", [1, 0, 0]],
        ["ren oo?", "did you?", [1, 0, 0]],
        ["cre ren oo?", "what did you?", [1, 0, 0]]
    ],
    fBigginyn: [
        ["biggin", "pet", [1, 0, 0]],
        ["bigginyn", "pet", [1, 0, 0]],
        ["vel biggin ayd?", "do you have a pet?", [1, 0, 0]],
        ["ta ... aym", "I have a ...", [1, 0, 0]],
        ["cha nel ... aym", "I don't have a ...", [1, 0, 0]],
        ["kayt", "cat", [0, 0, 0]],
        ["moddey", "dog", [0, 0, 0]],
        ["eeast", "fish", [0, 0, 0]],
        ["jerbyl", "gerbil", [0, 0, 0]],
        ["pussag", "hamster", [0, 0, 0]],
        ["lugh", "mouse", [0, 0, 0]],
        ["conning", "rabbit", [0, 0, 0]],
        ["garran", "pony", [0, 0, 0]],
        ["ushag", "bird", [0, 0, 0]],
        ["shligganagh", "tortoise", [0, 0, 0]],
        ["ardnieu", "snake", [0, 0, 0]]
    ],
    fEarrooyn20: [
        ["nane-jeig", "eleven", [0, 0, 0]],
        ["daa-yeig", "twelve", [0, 0, 0]],
        ["tree-jeig", "thirteen", [0, 0, 0]],
        ["kiare-jeig", "fourteen", [0, 0, 0]],
        ["queig-jeig", "fifteen", [0, 0, 0]],
        ["shey-jeig", "sixteen", [0, 0, 0]],
        ["shiaght-jeig", "seventeen", [0, 0, 0]],
        ["hoght-jeig", "eighteen", [0, 0, 0]],
        ["nuy-jeig", "nineteen", [0, 0, 0]],
        ["feed", "twenty", [0, 0, 0]]
    ],
    fDaahyn: [
        ["jiarg", "red", [0, 0, 0]],
        ["dhone", "brown", [0, 0, 0]],
        ["bwee", "yellow", [0, 0, 0]],
        ["glass", "green", [0, 0, 0]],
        ["gorrym", "blue", [0, 0, 0]],
        ["doo", "black", [0, 0, 0]],
        ["bane", "white", [0, 0, 0]]
    ]
};

let ooilleyNyFocklyn = [];
Object.values(focklynRyYnsagh).forEach(c => c.forEach(f => ooilleyNyFocklyn.push(f[0])));
console.log("Words learned: " + ooilleyNyFocklyn.length);